// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AssemblySourcemap { machine_code_to_asm: Array<number>, asm_to_machine_code: Record<number, number>, }