// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ASTNode<T> { node: T, node_idx: number, token_range: { start: number, end: number, }, }