// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BinaryOperator = "Plus" | "Minus" | "Multiply" | "Divide" | "And" | "Or" | "LessThan" | "LessThanOrEquals" | "GreaterThan" | "GreaterThanOrEquals" | "Equals";