// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ASTNode } from "./ASTNode";
import type { ClassVarDeclaration } from "./ClassVarDeclaration";
import type { SubroutineDeclaration } from "./SubroutineDeclaration";

export interface Class { name: string, var_declarations: Array<ASTNode<ClassVarDeclaration>>, subroutine_declarations: Array<ASTNode<SubroutineDeclaration>>, }