// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourcemappedCommand } from "./SourcemappedCommand";

export interface CompiledSubroutine { name: string, commands: Array<SourcemappedCommand>, locals_count: number, arg_count: number, }