// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssemblyResult } from "./AssemblyResult";
import type { JackCompilerResult } from "./JackCompilerResult";
import type { VMCompilerResult } from "./VMCompilerResult";

export interface CompilerResult { jack_compiler_result: JackCompilerResult, vm_compiler_result: VMCompilerResult, assembly_result: AssemblyResult, }