// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JackCodegenSourceMap } from "./JackCodegenSourceMap";
import type { JackParserSourceMap } from "./JackParserSourceMap";

export interface JackCompilerSourceMap { parser_sourcemap: JackParserSourceMap, codegen_sourcemap: JackCodegenSourceMap, }