// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface JackCodegenSourceMap { jack_node_idx_to_vm_command_idx: Record<number, Array<number>>, vm_command_idx_to_jack_node_idx: Record<number, number>, }