// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeywordTokenVariant = "Class" | "Constructor" | "Function" | "Method" | "Field" | "Static" | "Var" | "Int" | "Char" | "Boolean" | "Void" | "True" | "False" | "Null" | "This" | "Let" | "Do" | "If" | "Else" | "While" | "Return";