// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperatorVariant = "Plus" | "Minus" | "Star" | "Slash" | "Ampersand" | "Pipe" | "LessThan" | "LessThanOrEquals" | "GreaterThan" | "GreaterThanOrEquals" | "Equals" | "Tilde";