// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumericConstantVariant } from "./NumericConstantVariant";

export type PrimitiveTermVariant = { NumericConstant: NumericConstantVariant } | { StringConstant: string } | "True" | "False" | "Null" | "This";