// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VMCommandIdentifier } from "./VMCommandIdentifier";

export interface SourceMap { asm_instruction_idx_to_vm_cmd: Record<number, VMCommandIdentifier>, vm_filename_and_idx_to_asm_instruction_idx: Record<string, Record<number, Array<number>>>, }