// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ASTNode } from "./ASTNode";
import type { Statement } from "./Statement";
import type { VarDeclaration } from "./VarDeclaration";

export interface SubroutineBody { var_declarations: Array<ASTNode<VarDeclaration>>, statements: Array<ASTNode<Statement>>, }