// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeywordTokenVariant } from "./KeywordTokenVariant";
import type { OperatorVariant } from "./OperatorVariant";

export type TokenKind = { Keyword: KeywordTokenVariant } | { IntegerLiteral: string } | { StringLiteral: string } | { Identifier: string } | "LCurly" | "RCurly" | "LParen" | "RParen" | "LSquareBracket" | "RSquareBracket" | "Dot" | "Comma" | "Semicolon" | "Whitespace" | "SingleLineComment" | "MultiLineComment" | { Operator: OperatorVariant };