// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from "./Type";

export interface VarDeclaration { type_name: Type, var_names: Array<string>, }