// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceMap } from "./SourceMap";

export interface VMCompilerResult { sourcemap: SourceMap, instructions: Array<string>, }