[package]
name = "nand2tetris-emulation"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3

[dependencies]
cargo-llvm-cov = "0.4.8"
clap = { version = "3.1.13", features = ["derive"] }
minifb = "0.23.0"
regex = "1.5.5"
tabled = "0.7.0"
