#!/bin/bash

ssh -i ~/.ssh/A2D9A10570F977E8.pub deb \
  'cd dev/nand2tetris-emulation/fpga && docker run --privileged --mount type=bind,source="$(realpath xc7/counter_test)",target=/f4pga-examples/xc7/computer fpga \
  /bin/bash -c '\''make -C computer && make download -C computer'\'
