#!/bin/bash

set -euxo pipefail

scp -i ~/.ssh/A2D9A10570F977E8.pub -r ./fpga deb:/home/joe/dev/nand2tetris-emulation/fpga

ssh -o ServerAliveInterval=5 -o ServerAliveCountMax=10000 -i ~/.ssh/A2D9A10570F977E8.pub deb \
  'cd dev/nand2tetris-emulation/fpga/fpga && /media/ssd/Xilinx/Vivado/2023.2/bin/vivado -mode batch -nojournal -source build.tcl'
