#!/usr/bin/env bash

set -eu

cd core
cargo run -- debug-compile ../std_lib/Memory.jack ../web/debug-output.json

# cargo test || true
# # get data for viz
# cargo run -- jack-parser-viz ../std_lib/Math.jack

# cd ../web
# npm start
