// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassVarDeclarationKind } from "./ClassVarDeclarationKind";
import type { Type } from "./Type";
import type { VarNames } from "./VarNames";

export interface ClassVarDeclaration { type_name: Type, qualifier: ClassVarDeclarationKind, var_names: VarNames, source_byte_range: { start: number, end: number, }, }