// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassVarDeclarationKindVariant } from "./ClassVarDeclarationKindVariant";

export interface ClassVarDeclarationKind { variant: ClassVarDeclarationKindVariant, source_byte_range: { start: number, end: number, }, }