// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassVarDeclarationKind } from "./ClassVarDeclarationKind";
import type { Type } from "./Type";

export interface ClassVarDeclaration { type_name: Type, qualifier: [ClassVarDeclarationKind, number], var_names: Array<string>, }