// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassVarDeclaration } from "./ClassVarDeclaration";
import type { IndexedJackNode } from "./IndexedJackNode";
import type { SubroutineDeclaration } from "./SubroutineDeclaration";

export interface Class { name: string, var_declarations: Array<IndexedJackNode<ClassVarDeclaration>>, subroutine_declarations: Array<[SubroutineDeclaration, number]>, }