// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceMap } from "./SourceMap";
import type { Token } from "./Token";
import type { TokenKind } from "./TokenKind";

export interface DebugOutput { tokens: Array<Token<TokenKind>>, sourcemap: SourceMap, vm_commands: Array<string>, }