// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JackCompilerSourceMap } from "./JackCompilerSourceMap";
import type { Token } from "./Token";
import type { TokenKind } from "./TokenKind";

export interface DebugOutput { tokens: Record<string, Array<Token<TokenKind>>>, sourcemap: JackCompilerSourceMap, vm_commands: Array<string>, }