// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryOperator } from "./BinaryOperator";
import type { IndexedJackNode } from "./IndexedJackNode";
import type { PrimitiveTermVariant } from "./PrimitiveTermVariant";
import type { SubroutineCall } from "./SubroutineCall";
import type { UnaryOperator } from "./UnaryOperator";

export type Expression = { Parenthesized: IndexedJackNode<Expression> } | { PrimitiveTerm: PrimitiveTermVariant } | { Binary: { operator: BinaryOperator, lhs: IndexedJackNode<Expression>, rhs: IndexedJackNode<Expression>, } } | { Unary: { operator: UnaryOperator, operand: IndexedJackNode<Expression>, } } | { Variable: string } | { SubroutineCall: [SubroutineCall, number] } | { ArrayAccess: { var_name: string, index: IndexedJackNode<Expression>, } };