// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryOperator } from "./BinaryOperator";
import type { PrimitiveTermVariant } from "./PrimitiveTermVariant";
import type { SubroutineCall } from "./SubroutineCall";
import type { UnaryOperator } from "./UnaryOperator";

export type Expression = { Parenthesized: [Expression, number] } | { PrimitiveTerm: PrimitiveTermVariant } | { Binary: { operator: BinaryOperator, lhs: [Expression, number], rhs: [Expression, number], } } | { Unary: { operator: UnaryOperator, operand: [Expression, number], } } | { Variable: string } | { SubroutineCall: [SubroutineCall, number] } | { ArrayAccess: { var_name: string, index: [Expression, number], } };