// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Identifier { name: string, source_byte_range: { start: number, end: number, }, }