// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JackCompilerSourceMap } from "./JackCompilerSourceMap";
import type { Token } from "./Token";
import type { TokenKind } from "./TokenKind";

export interface JackCompilerResult { filename: string, tokens: Array<Token<TokenKind>>, sourcemap: JackCompilerSourceMap, commands: Array<string>, }