// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfo } from "./NodeInfo";

export interface JackParserSourceMap { token_idx_to_jack_node_idxs: Record<string, Record<number, Array<number>>>, jack_nodes: Record<string, Array<NodeInfo>>, }