// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NodeInfo { token_range: { start: number, end: number, }, child_node_idxs: Array<number>, }