// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { Type } from "./Type";

export interface Parameter { type_name: Type, var_name: Identifier, source_byte_range: { start: number, end: number, }, }