// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfo } from "./NodeInfo";

export interface SourceMap { token_idx_to_jack_node_idxs: Record<string, Record<number, Array<number>>>, jack_nodes: Array<NodeInfo>, jack_node_idx_to_vm_command_idx: Record<number, Array<number>>, vm_command_idx_to_jack_node_idx: Record<number, number>, }