// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";
import type { SubroutineCall } from "./SubroutineCall";

export type Statement = { Let: { var_name: string, array_index: Expression | null, value: Expression, } } | { If: { condition: Expression, if_statements: Array<Statement>, else_statements: Array<Statement> | null, } } | { While: { condition: Expression, statements: Array<Statement>, } } | { Do: SubroutineCall } | { Return: Expression | null };