// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexedJackNode } from "./IndexedJackNode";
import type { Statement } from "./Statement";
import type { VarDeclaration } from "./VarDeclaration";

export interface SubroutineBody { var_declarations: Array<IndexedJackNode<VarDeclaration>>, statements: Array<IndexedJackNode<Statement>>, }