// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";
import type { Identifier } from "./Identifier";

export type SubroutineCall = { Direct: { subroutine_name: Identifier, arguments: Array<Expression>, } } | { Method: { this_name: Identifier, method_name: Identifier, arguments: Array<Expression>, } };