// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";
import type { IndexedJackNode } from "./IndexedJackNode";

export type SubroutineCall = { Direct: { subroutine_name: string, arguments: Array<IndexedJackNode<Expression>>, } } | { Method: { this_name: string, method_name: string, arguments: Array<IndexedJackNode<Expression>>, } };