// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { Parameter } from "./Parameter";
import type { SubroutineBody } from "./SubroutineBody";
import type { SubroutineKind } from "./SubroutineKind";
import type { Type } from "./Type";

export interface SubroutineDeclaration { subroutine_kind: SubroutineKind, return_type: Type | null, parameters: Array<Parameter>, name: Identifier, body: SubroutineBody, source_byte_range: { start: number, end: number, }, }