// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeVariant } from "./TypeVariant";

export interface Type { variant: TypeVariant, source_byte_range: { start: number, end: number, }, }