// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

export type Type = "Int" | "Char" | "Boolean" | { ClassName: Identifier };