// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from "./Type";
import type { VarNames } from "./VarNames";

export interface VarDeclaration { type_name: Type, var_names: VarNames, }