// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

export interface VarNames { names: Array<Identifier>, source_byte_range: { start: number, end: number, }, }